spring:
  application:
    name: member
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.203.128:3306/gulimall_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8333
        port: 8719
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: 192.168.203.128
    port: 6379

mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: '*'
