spring:
  application:
    name: member
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.203.128:3306/gulimall_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8333
        port: 8719
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: 192.168.203.128
    port: 6379
  zipkin:
    base-url: http://192.168.203.128:9411 #配置url地址收集链路信息
    discovery-client-enabled: false #不开启服务发现功能
    sender:
      type: web #传输数据的方式
  sleuth:
    sampler:
      probability: 1 #链路信息抽样采集率，1表示100%，默认0.1（10%）

mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true
